import Head from 'next/head'
import { Container } from '@/components/container/Container'
import { MyContext } from '@/context/Mycontext'
import { createGlobalStyle } from 'styled-components'

export default function Home() {
  const GlobalStyle = createGlobalStyle`
  body{
    padding:0;
    margin:0;
    box-sizing: border-box;
  }
 `

  return (
    <>
      <Head>
        <title>age-counter</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <MyContext.Provider value={{}}>
        <GlobalStyle />
        <Container>
          é só um teste boy
        </Container>
      </MyContext.Provider>
    </>
  )
}
